### ISSUE TITLE
Add wiring details to app

### ISSUE THREAD

**Issue by Firstyear** [NaejEL/flipperzero-i2ctools#5]
Many other flipper apps show their wiring configuration within the app, either on a menu or some other graphic. It would assist new users of this application for your wiring layout (as shown in your readme) to be a part of the apps main menu, or for there to be a "wiring" option on that menu that shows the required wiring setup. Thanks!

**Comment by NaejEL** [comment]
Good Idea

**Comment by NaejEL** [comment]
Done in commit bf47633
Thanks @Firstyear
