### ISSUE TITLE
i2cTools_icons.h is missing from the repo?

### ISSUE THREAD

**Issue by Numbski** [NaejEL/flipperzero-i2ctools#6]
I'm trying to build this code, but multiple files reference this header, and and I don't see the header anywhere in the repo.  Is this a mistake, or am I supposed to generate this file somehow?

**Comment by NaejEL** [comment]
Hi,
FBT is supposed to build this file at compile time. Maybe an update of the
API broke this. Due to lot of work, I don't have time to maintain this
repo. Hope I will have soon to add some features and follow flipper APIs
change.

Le lun. 26 juin 2023 à 23:55, Tony Shadwick ***@***.***> a
écrit :

**Comment by Numbski** [comment]
I think I might know what happened.  There was a section of the files that when I tried to build with ufbt complained because of capitalization, so I lower-cased it.

I bet what is happening now is that the file gets created, but is named wrong.  Will try again.

Thanks!

Tony Shadwick

**Comment by Numbski** [comment]
That was precisely the problem.  Sorry to bother you!

Tony Shadwick

**Comment by NaejEL** [comment]
> 

Thanks,
I made the changes, no uppercase allowed in appid.
If it's works for you I'll close the issue.
Thanks again, you don't bother me ;)

**Comment by NaejEL** [comment]
I confirm it's fixed. I close the issue
